const SocketConst = {
  SEND_REQUEST: "SEND_REQUEST",
  NEW_REQUEST: "NEW_REQUEST",
  JOIN_ON_ROOM: "JOIN_ON_ROOM",
  INITIATE_REQUEST: "INITIATE_REQUEST",
  REQUEST_RESPONSE: "REQUEST_RESPONSE",
  REQUEST_ACCEPTED: "REQUEST_ACCEPTED",
  GET_REQUEST: "GET_REQUEST",
  ANSWER_OF_REQUEST: "ANSWER_OF_REQUEST",
  REJECT_REQUEST: "REJECT_REQUEST",
};

module.exports = SocketConst;
